version: "3.3"

services:
  ports:
    image: ports
    container_name: ports_dev
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - PORTS_HTTP_LISTEN_ADDR=:8080
      - PORTS_MONGODB_CONN_URI=mongodb://mongo:27017/ports
    depends_on:
      - mongo
    networks:
      - local_net

  mongo:
    image: bitnami/mongodb:4 # Latest versions do not work as expected on ARM64.
    container_name: ports_mongodb
    environment:
      - MONGODB_DISABLE_SYSTEM_LOG=true
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=0.25
      - ALLOW_EMPTY_PASSWORD=true
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/ports/data/db
    networks:
      - local_net

volumes:
  mongodb:

networks:
  local_net: